# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Amicus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Amicus_Frontend
  pod 'SwiftUIFormValidator'

  target 'AmicusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AmicusUITests' do
    # Pods for testing
  end

end
